version: '2'
services:
    merge-app:
        image: merge
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://merge-mysql:3306/merge?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    merge-mysql:
        extends:
            file: mysql.yml
            service: merge-mysql
